### ISSUE TITLE
EarlyOOM is amazing! 

### ISSUE THREAD

**Issue by Overc1ocker** [rfjakob/earlyoom#233] opened 2020-12-14 04:39 UTC
I use linux as a daily driver and had I not discovered this, I probably would've had my computer lock up in the middle of a very stressful time. Instead, EarlyOOM verified I had enough RAM to keep going. THANK YOU!!

**Comment by jayenashar** [comment] 2020-12-14 04:42
duplicate of #232?

**Comment by rfjakob** [comment] 2020-12-20 18:30
Thanks :)

**Closed by rfjakob** 2020-12-20 18:30 UTC
