### ISSUE TITLE
fopen 5466/oom_score failed: No such file or directory

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [rfjakob/earlyoom#117] opened 2019-02-18 04:51 UTC
`fopen 5466/oom_score failed: No such file or directory`

Is this a bug? I see it - that message - twice after restarting the systemd service. Thanks.

Linux Mint 19.1 x64 Cinnamon
earlyoom v1.2-26-g7cdb65c

**Comment by hakavlad** [comment] 2019-02-27 11:09
@LinuxOnTheDesktop It's not a bug. It's just info.

@rfjakob What about skip this message? Or print this only with --debug.

**Comment by rfjakob** [comment] 2019-04-27 15:34
Fixed via https://github.com/rfjakob/earlyoom/commit/61ef7c0ad35fd397b993a3555ffff42dda1a0b78 . "No such file or directory" messages are suppressed because they are useless. Other errors are still shown.

**Closed by rfjakob** 2019-04-27 15:34 UTC
